spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4G1wCMMMoQSrF5nwCiSC
      secret-key: RXUTgCBOCmNKigMJz1Yf6YEdgZUhIQ
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-hello-images
  application:
    name: gulimall-third-party
server:
  port: 30000
